// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA02HG2zphWhb4RfiscC97MyvlLTSTPTYI',
    appId: '1:283247133770:web:7878dec34a585ce516d2b3',
    messagingSenderId: '283247133770',
    projectId: 'e-commerce-app-44b37',
    authDomain: 'e-commerce-app-44b37.firebaseapp.com',
    storageBucket: 'e-commerce-app-44b37.firebasestorage.app',
    measurementId: 'G-Q3QR24FR3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZks9utNOtzivKK6lJUI26S03nq8Umw8g',
    appId: '1:283247133770:android:c84c0c879b95893716d2b3',
    messagingSenderId: '283247133770',
    projectId: 'e-commerce-app-44b37',
    storageBucket: 'e-commerce-app-44b37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDADx3q-Hj3hcVweMajyNg668EVXI4VbyM',
    appId: '1:283247133770:ios:a14e40c1b958f61116d2b3',
    messagingSenderId: '283247133770',
    projectId: 'e-commerce-app-44b37',
    storageBucket: 'e-commerce-app-44b37.firebasestorage.app',
    androidClientId: '283247133770-c9af1cn138elpjeohcg28t4g6vcis17q.apps.googleusercontent.com',
    iosClientId: '283247133770-90rhof4nf75nu9fpt8tird8jlvugp40k.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDADx3q-Hj3hcVweMajyNg668EVXI4VbyM',
    appId: '1:283247133770:ios:a14e40c1b958f61116d2b3',
    messagingSenderId: '283247133770',
    projectId: 'e-commerce-app-44b37',
    storageBucket: 'e-commerce-app-44b37.firebasestorage.app',
    androidClientId: '283247133770-c9af1cn138elpjeohcg28t4g6vcis17q.apps.googleusercontent.com',
    iosClientId: '283247133770-90rhof4nf75nu9fpt8tird8jlvugp40k.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA02HG2zphWhb4RfiscC97MyvlLTSTPTYI',
    appId: '1:283247133770:web:cb7ead3707c462fa16d2b3',
    messagingSenderId: '283247133770',
    projectId: 'e-commerce-app-44b37',
    authDomain: 'e-commerce-app-44b37.firebaseapp.com',
    storageBucket: 'e-commerce-app-44b37.firebasestorage.app',
    measurementId: 'G-RT2Q6N2PG8',
  );

}